import React, { useMemo } from 'react';
import { useGLTF, Center } from '@react-three/drei';
import FalconModel from '../assets/3d/star_wars_millennium_falcon.glb';

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Brad Short (https://sketchfab.com/dbshort)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/star-wars-millennium-falcon-f7752038addb4ba1bbd5783ac44bd989
Title: Star Wars Millennium Falcon
*/
const MillenniumFalcon = ({ ...props }) => {
  const { scene } = useGLTF(FalconModel);
  const clone = useMemo(() => scene.clone(true), [scene]);

  return (
    <group {...props}>
      <Center>
        <primitive object={clone} />
      </Center>
    </group>
  );
};

useGLTF.preload(FalconModel);
export default MillenniumFalcon;
