import React, { useEffect } from 'react';
import FalconModel from '../assets/3d/star_wars_millennium_falcon.glb';
import { useGLTF } from '@react-three/drei';

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Brad Short (https://sketchfab.com/dbshort)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/star-wars-millennium-falcon-f7752038addb4ba1bbd5783ac44bd989
Title: Star Wars Millennium Falcon
*/
const MillenniumFalcon = (props) => {
  const { scene } = useGLTF(FalconModel);

  useEffect(() => {
    console.debug('[MillenniumFalcon] Loaded scene:', scene);
  }, [scene]);

  return (
    <group {...props}>
      <primitive object={scene} />
    </group>
  );
};

useGLTF.preload(FalconModel);

export default MillenniumFalcon;
