/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: JanesBT (https://sketchfab.com/JanesBt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/moon-fc1e78cfc65549c6a49e88ba599b7901
Title: Moon
*/
import React from 'react';
import PlanetModel from '../assets/3d/Planet.glb';
import { useGLTF } from '@react-three/drei';

const Planet = () => {
    const { scene, animations } = useGLTF(PlanetModel);
    return (
        <mesh position={[0, 0, 0]} scale={1,1,1}>
            <primitive object={scene} />
        </mesh>
    );
}

export default Planet;