import React from 'react';
import SpaceModel from '../assets/3d/Space.glb';
import { useGLTF } from '@react-three/drei';

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MozillaHubs (https://sketchfab.com/mozillareality)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/sky-pano-milkyway-0016725c047a4ea18cd0b5e5ef2fe441
Title: Sky Pano - Milkyway
*/

const Space = () => {
    const { scene } = useGLTF(SpaceModel);

    return (
        <primitive
            object={scene}
            position={[0, 0, -100]}      // Far back
            scale={[80, 80, 80]}         // Huge scale
        />
    );
};

export default Space;
