/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MozillaHubs (https://sketchfab.com/mozillareality)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/sky-pano-milkyway-0016725c047a4ea18cd0b5e5ef2fe441
Title: Sky Pano - Milkyway
*/

import React, { forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';
import SpaceModel from '../assets/3d/Space.glb';

const Space = forwardRef((props, ref) => {
  const { scene } = useGLTF(SpaceModel);

  return (
    <group ref={ref} {...props}>
      <primitive object={scene} />
    </group>
  );
});

export default Space;

