/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Mickael Boitte (https://sketchfab.com/boittemike1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-tie-fighter-star-wars-model-5375de94c2484ab0b2a2bd75aa63c2b4
Title: 3D T.I.E Fighter - Star Wars model
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber';
import { a } from '@react-spring/three';
import TieFighterScene from '../assets/3d/tie_fighter.glb'

const TieFighter = (props) => {
    const tieFighterRef = useRef();

    const { nodes, materials } = useGLTF(TieFighterScene)
    return (
        <a.group {...props} ref={tieFighterRef}>
            <group position={[0.68, -0.141, 0.358]} rotation={[-1.794, -0.3, -0.17]} scale={0.736}>
                <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001']} />
                <mesh geometry={nodes.Object_3.geometry} material={materials['Material.002']} />
                <mesh geometry={nodes.Object_4.geometry} material={materials['Material.003']} />
            </group>
        </a.group>
    )
}

useGLTF.preload(TieFighterScene)

export default TieFighter;