import React, { useRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import { a } from '@react-spring/three';
import TieFighterScene from '../assets/3d/tie_fighter.glb';

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Mickael Boitte (https://sketchfab.com/boittemike1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-tie-fighter-star-wars-model-5375de94c2484ab0b2a2bd75aa63c2b4
Title: 3D T.I.E Fighter - Star Wars model
*/

const TieFighter = (props) => {
    const tieFighterRef = useRef();
    const { scene } = useGLTF(TieFighterScene);

    useEffect(() => {
        scene.traverse((child) => {
            if (child.isMesh) {
                const original = child.material;

                child.material = new THREE.MeshStandardMaterial({
                    color: original.color || new THREE.Color('white'),
                    map: original.map || null,
                    normalMap: original.normalMap || null,
                    metalnessMap: original.metalnessMap || null,
                    roughnessMap: original.roughnessMap || null,
                    metalness: 0.5,
                    roughness: 0.4,
                });

                child.castShadow = true;
                child.receiveShadow = true;
            }
        });
    }, [scene]);

    return (
        <a.group {...props} ref={tieFighterRef}>
            <primitive object={scene} />
        </a.group>
    );
};

useGLTF.preload(TieFighterScene);

export default TieFighter;
