import React from 'react';
import XwingModel from '../assets/3d/x_wing.glb';
import { useGLTF } from '@react-three/drei';

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: juan.casado (https://sketchfab.com/juan.casado)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/x-wing-53ad850f929c4ea0897df842422533a4
Title: x wing
*/
const XWing = (props) => {
    const { scene } = useGLTF(XwingModel);

    return (
        <group {...props}>
            <primitive object={scene} />
        </group>
    );
};

export default XWing;
